version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-boot-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/hotel_management
      SPRING_DATASOURCE_USERNAME: "hotel_admin"
      SPRING_DATASOURCE_PASSWORD: "hotel_pass"
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

  db:
    image: postgres:15
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: hotel_management
      POSTGRES_USER: "hotel_admin"
      POSTGRES_PASSWORD: "hotel_pass"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: