version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-boot-app
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/target
    environment:
      - SPRING_DATASOURCE_URL=mongodb://db:27017/hotel_management
      - SPRING_DATASOURCE_USERNAME=hotel_admin
      - SPRING_DATASOURCE_PASSWORD=hotel_pass
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db

  db:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: